/**
 * summary-merging.test.ts — Unit tests for cross-session summary merging.
 *
 * Validates that parsePreviousSummary() correctly extracts Overview table
 * totals from an existing _SUMMARY.md file, enabling cross-session merging
 * when the pipeline resumes in a new orchestrator session.
 *
 * Uses Node.js built-in test runner (node:test) — zero dependencies.
 * Run: npx tsx src/__tests__/summary-merging.test.ts
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { parsePreviousSummary, formatDuration, formatUsd } from "../reporting.js";

// ---------------------------------------------------------------------------
// parsePreviousSummary
// ---------------------------------------------------------------------------

describe("parsePreviousSummary", () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "summary-test-"));

  it("returns null for non-existent file", () => {
    const result = parsePreviousSummary(path.join(tmpDir, "nonexistent.md"));
    assert.equal(result, null);
  });

  it("returns null for file without Overview table", () => {
    const filePath = path.join(tmpDir, "no-overview.md");
    fs.writeFileSync(filePath, "# Pipeline Summary\n\nNo table here.\n");
    const result = parsePreviousSummary(filePath);
    assert.equal(result, null);
  });

  it("parses a well-formed Overview table", () => {
    const filePath = path.join(tmpDir, "good-summary.md");
    const content = [
      "# Pipeline Summary — test-feature",
      "",
      "> Auto-generated by the orchestrator on 2026-03-15T10:30:00.000Z",
      "",
      "## Overview",
      "",
      "| Metric | Value |",
      "|---|---|",
      "| Total steps | 8 (6 passed, 2 failed/errored) |",
      "| Total duration | 12m 45s |",
      "| Files changed | 23 |",
      "| Total tokens | 1,234,567 |",
      "| **Estimated cost** | **$18.5432** |",
      "| Cost per file changed | $0.8062 |",
      "",
      "## Steps",
      "",
    ].join("\n");
    fs.writeFileSync(filePath, content);

    const result = parsePreviousSummary(filePath);
    assert.ok(result !== null);
    assert.equal(result.steps, 8);
    assert.equal(result.completed, 6);
    assert.equal(result.failed, 2);
    assert.equal(result.durationMs, 12 * 60_000 + 45 * 1_000); // 12m 45s
    assert.equal(result.filesChanged, 23);
    assert.equal(result.tokens, 1234567);
    assert.equal(result.costUsd, 18.5432);
  });

  it("parses a summary with only seconds duration", () => {
    const filePath = path.join(tmpDir, "seconds-only.md");
    const content = [
      "| Metric | Value |",
      "|---|---|",
      "| Total steps | 3 (3 passed, 0 failed/errored) |",
      "| Total duration | 45s |",
      "| Files changed | 5 |",
      "| Total tokens | 50,000 |",
      "| **Estimated cost** | **$1.2500** |",
    ].join("\n");
    fs.writeFileSync(filePath, content);

    const result = parsePreviousSummary(filePath);
    assert.ok(result !== null);
    assert.equal(result.steps, 3);
    assert.equal(result.completed, 3);
    assert.equal(result.failed, 0);
    assert.equal(result.durationMs, 45_000);
    assert.equal(result.filesChanged, 5);
    assert.equal(result.tokens, 50000);
  });

  it("parses a summary with milliseconds duration", () => {
    const filePath = path.join(tmpDir, "ms-only.md");
    const content = [
      "| Metric | Value |",
      "|---|---|",
      "| Total steps | 1 (1 passed, 0 failed/errored) |",
      "| Total duration | 500ms |",
      "| Files changed | 1 |",
      "| Total tokens | 1,000 |",
      "| **Estimated cost** | **$0.0100** |",
    ].join("\n");
    fs.writeFileSync(filePath, content);

    const result = parsePreviousSummary(filePath);
    assert.ok(result !== null);
    assert.equal(result.durationMs, 500);
  });

  it("parses a summary with merge note from a prior merge", () => {
    const filePath = path.join(tmpDir, "already-merged.md");
    const content = [
      "| Metric | Value |",
      "|---|---|",
      "| Total steps | 12 (10 passed, 2 failed/errored) (includes 4 steps from prior session) |",
      "| Total duration | 25m |",
      "| Files changed | 42 |",
      "| Total tokens | 2,000,000 |",
      "| **Estimated cost** | **$30.0000** |",
    ].join("\n");
    fs.writeFileSync(filePath, content);

    const result = parsePreviousSummary(filePath);
    assert.ok(result !== null);
    assert.equal(result.steps, 12);
    assert.equal(result.completed, 10);
    assert.equal(result.failed, 2);
    assert.equal(result.durationMs, 25 * 60_000);
  });
});

// ---------------------------------------------------------------------------
// baseTelemetry monotonic merge (boot-time parse + unconditional add)
// ---------------------------------------------------------------------------

import { writePipelineSummary, type PreviousSummaryTotals } from "../reporting.js";
import type { ItemSummary } from "../types.js";

/** Build a minimal valid ItemSummary for testing */
function makeSummary(overrides: Partial<ItemSummary> = {}): ItemSummary {
  return {
    key: "test-step",
    label: "Test Step",
    agent: "test-agent",
    phase: "dev",
    attempt: 1,
    startedAt: new Date().toISOString(),
    finishedAt: new Date().toISOString(),
    durationMs: 60_000,
    outcome: "completed",
    intents: [],
    messages: [],
    filesRead: [],
    filesChanged: ["src/foo.ts"],
    shellCommands: [],
    toolCounts: {},
    inputTokens: 5000,
    outputTokens: 2000,
    cacheReadTokens: 0,
    cacheWriteTokens: 0,
    ...overrides,
  };
}

describe("baseTelemetry merge", () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "base-tel-test-"));
  // writePipelineSummary expects: appRoot/in-progress/<slug>_SUMMARY.md
  const fakeAppRoot = path.join(tmpDir, "app");
  const fakeRepoRoot = tmpDir;
  const slug = "test-merge";

  // Create the in-progress directory
  fs.mkdirSync(path.join(fakeAppRoot, "in-progress"), { recursive: true });

  const summaryFile = path.join(fakeAppRoot, "in-progress", `${slug}_SUMMARY.md`);

  it("writes correct totals with null baseTelemetry", () => {
    const summaries = [makeSummary({ durationMs: 30_000 })];
    writePipelineSummary(fakeAppRoot, fakeRepoRoot, slug, summaries, undefined, null);
    const content = fs.readFileSync(summaryFile, "utf-8");
    assert.match(content, /Total steps \| 1/);
    assert.ok(!content.includes("prior session"));
  });

  it("adds baseTelemetry to current totals", () => {
    const base: PreviousSummaryTotals = {
      steps: 5, completed: 4, failed: 1,
      durationMs: 300_000, filesChanged: 10, tokens: 100_000, costUsd: 5.0,
    };
    const summaries = [makeSummary({ durationMs: 60_000 })];
    writePipelineSummary(fakeAppRoot, fakeRepoRoot, slug, summaries, undefined, base);
    const content = fs.readFileSync(summaryFile, "utf-8");
    // 1 current + 5 prior = 6 total steps
    assert.match(content, /Total steps \| 6/);
    assert.match(content, /includes 5 steps from prior session/);
  });

  it("stays monotonic when current steps equal prior steps", () => {
    // This is the exact scenario that broke the old shouldMerge approach:
    // Wave 1 wrote 5 steps, Wave 2 also has 5 steps => old guard dropped Wave 1
    const base: PreviousSummaryTotals = {
      steps: 5, completed: 5, failed: 0,
      durationMs: 200_000, filesChanged: 8, tokens: 80_000, costUsd: 3.0,
    };
    const summaries = Array.from({ length: 5 }, (_, i) =>
      makeSummary({ key: `step-${i}`, durationMs: 40_000 }),
    );
    writePipelineSummary(fakeAppRoot, fakeRepoRoot, slug, summaries, undefined, base);
    const content = fs.readFileSync(summaryFile, "utf-8");
    // 5 current + 5 prior = 10 total steps (NOT 5!)
    assert.match(content, /Total steps \| 10/);
    assert.match(content, /includes 5 steps from prior session/);
  });

  it("stays monotonic when current steps exceed prior steps", () => {
    const base: PreviousSummaryTotals = {
      steps: 3, completed: 3, failed: 0,
      durationMs: 100_000, filesChanged: 5, tokens: 30_000, costUsd: 1.0,
    };
    const summaries = Array.from({ length: 7 }, (_, i) =>
      makeSummary({ key: `step-${i}`, durationMs: 20_000 }),
    );
    writePipelineSummary(fakeAppRoot, fakeRepoRoot, slug, summaries, undefined, base);
    const content = fs.readFileSync(summaryFile, "utf-8");
    // 7 current + 3 prior = 10 total steps
    assert.match(content, /Total steps \| 10/);
  });

  it("round-trips: write then parse yields correct baseTelemetry for next boot", () => {
    const base: PreviousSummaryTotals = {
      steps: 4, completed: 3, failed: 1,
      durationMs: 180_000, filesChanged: 12, tokens: 60_000, costUsd: 2.5,
    };
    const summaries = [
      makeSummary({ durationMs: 60_000, filesChanged: ["a.ts", "b.ts"] }),
      makeSummary({ key: "s2", durationMs: 30_000, outcome: "failed", filesChanged: ["c.ts"] }),
    ];
    writePipelineSummary(fakeAppRoot, fakeRepoRoot, slug, summaries, undefined, base);

    // Simulate next boot: parse the file we just wrote
    const parsed = parsePreviousSummary(summaryFile);
    assert.ok(parsed !== null);
    // 2 current + 4 prior = 6 total steps
    assert.equal(parsed.steps, 6);
    // 1 current completed + 3 prior = 4
    assert.equal(parsed.completed, 4);
    // 1 current failed + 1 prior = 2
    assert.equal(parsed.failed, 2);
  });
});

// ---------------------------------------------------------------------------
// Sanity checks for formatting helpers (used by merge)
// ---------------------------------------------------------------------------

describe("formatDuration (merge-relevant cases)", () => {
  it("formats minutes and seconds", () => {
    assert.equal(formatDuration(765_000), "12m 45s");
  });

  it("formats exact minutes", () => {
    assert.equal(formatDuration(300_000), "5m");
  });

  it("formats sub-minute", () => {
    assert.equal(formatDuration(45_000), "45s");
  });

  it("formats sub-second", () => {
    assert.equal(formatDuration(500), "500ms");
  });
});

describe("formatUsd", () => {
  it("formats with 4 decimal places", () => {
    assert.equal(formatUsd(18.5432), "$18.5432");
  });

  it("formats zero", () => {
    assert.equal(formatUsd(0), "$0.0000");
  });
});
