/**
 * summary-merging.test.ts — Unit tests for cross-session summary merging.
 *
 * Validates that parsePreviousSummary() correctly extracts Overview table
 * totals from an existing _SUMMARY.md file, enabling cross-session merging
 * when the pipeline resumes in a new orchestrator session.
 *
 * Uses Node.js built-in test runner (node:test) — zero dependencies.
 * Run: npx tsx src/__tests__/summary-merging.test.ts
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { parsePreviousSummary, formatDuration, formatUsd } from "../reporting.js";

// ---------------------------------------------------------------------------
// parsePreviousSummary
// ---------------------------------------------------------------------------

describe("parsePreviousSummary", () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "summary-test-"));

  it("returns null for non-existent file", () => {
    const result = parsePreviousSummary(path.join(tmpDir, "nonexistent.md"));
    assert.equal(result, null);
  });

  it("returns null for file without Overview table", () => {
    const filePath = path.join(tmpDir, "no-overview.md");
    fs.writeFileSync(filePath, "# Pipeline Summary\n\nNo table here.\n");
    const result = parsePreviousSummary(filePath);
    assert.equal(result, null);
  });

  it("parses a well-formed Overview table", () => {
    const filePath = path.join(tmpDir, "good-summary.md");
    const content = [
      "# Pipeline Summary — test-feature",
      "",
      "> Auto-generated by the orchestrator on 2026-03-15T10:30:00.000Z",
      "",
      "## Overview",
      "",
      "| Metric | Value |",
      "|---|---|",
      "| Total steps | 8 (6 passed, 2 failed/errored) |",
      "| Total duration | 12m 45s |",
      "| Files changed | 23 |",
      "| Total tokens | 1,234,567 |",
      "| **Estimated cost** | **$18.5432** |",
      "| Cost per file changed | $0.8062 |",
      "",
      "## Steps",
      "",
    ].join("\n");
    fs.writeFileSync(filePath, content);

    const result = parsePreviousSummary(filePath);
    assert.ok(result !== null);
    assert.equal(result.steps, 8);
    assert.equal(result.completed, 6);
    assert.equal(result.failed, 2);
    assert.equal(result.durationMs, 12 * 60_000 + 45 * 1_000); // 12m 45s
    assert.equal(result.filesChanged, 23);
    assert.equal(result.tokens, 1234567);
    assert.equal(result.costUsd, 18.5432);
  });

  it("parses a summary with only seconds duration", () => {
    const filePath = path.join(tmpDir, "seconds-only.md");
    const content = [
      "| Metric | Value |",
      "|---|---|",
      "| Total steps | 3 (3 passed, 0 failed/errored) |",
      "| Total duration | 45s |",
      "| Files changed | 5 |",
      "| Total tokens | 50,000 |",
      "| **Estimated cost** | **$1.2500** |",
    ].join("\n");
    fs.writeFileSync(filePath, content);

    const result = parsePreviousSummary(filePath);
    assert.ok(result !== null);
    assert.equal(result.steps, 3);
    assert.equal(result.completed, 3);
    assert.equal(result.failed, 0);
    assert.equal(result.durationMs, 45_000);
    assert.equal(result.filesChanged, 5);
    assert.equal(result.tokens, 50000);
  });

  it("parses a summary with milliseconds duration", () => {
    const filePath = path.join(tmpDir, "ms-only.md");
    const content = [
      "| Metric | Value |",
      "|---|---|",
      "| Total steps | 1 (1 passed, 0 failed/errored) |",
      "| Total duration | 500ms |",
      "| Files changed | 1 |",
      "| Total tokens | 1,000 |",
      "| **Estimated cost** | **$0.0100** |",
    ].join("\n");
    fs.writeFileSync(filePath, content);

    const result = parsePreviousSummary(filePath);
    assert.ok(result !== null);
    assert.equal(result.durationMs, 500);
  });

  it("parses a summary with merge note from a prior merge", () => {
    const filePath = path.join(tmpDir, "already-merged.md");
    const content = [
      "| Metric | Value |",
      "|---|---|",
      "| Total steps | 12 (10 passed, 2 failed/errored) (includes 4 steps from prior session) |",
      "| Total duration | 25m |",
      "| Files changed | 42 |",
      "| Total tokens | 2,000,000 |",
      "| **Estimated cost** | **$30.0000** |",
    ].join("\n");
    fs.writeFileSync(filePath, content);

    const result = parsePreviousSummary(filePath);
    assert.ok(result !== null);
    assert.equal(result.steps, 12);
    assert.equal(result.completed, 10);
    assert.equal(result.failed, 2);
    assert.equal(result.durationMs, 25 * 60_000);
  });
});

// ---------------------------------------------------------------------------
// shouldMerge guard logic (mirrors reporting.ts conditional)
// ---------------------------------------------------------------------------

describe("shouldMerge guard", () => {
  // Replicate the merge condition: prev.steps > summaries.length
  function shouldMerge(prev: { steps: number } | null, currentLength: number): boolean {
    return prev !== null && prev.steps > currentLength;
  }

  it("does NOT merge within same session (prev.steps === current.length)", () => {
    // After writing 5 steps, re-reading the same file gives prev.steps=5
    // and pipelineSummaries still has 5 entries => no merge
    assert.equal(shouldMerge({ steps: 5 }, 5), false);
  });

  it("does NOT merge when current session has MORE steps than prev", () => {
    // Prev file had 3 steps, but we now have 5 in memory => no merge
    assert.equal(shouldMerge({ steps: 3 }, 5), false);
  });

  it("DOES merge when prev file has MORE steps than current batch", () => {
    // Prev session wrote 8 steps, we resumed with 3 new ones => merge
    assert.equal(shouldMerge({ steps: 8 }, 3), true);
  });

  it("does NOT merge when prev is null", () => {
    assert.equal(shouldMerge(null, 5), false);
  });

  it("does NOT merge when prev.steps is 0", () => {
    assert.equal(shouldMerge({ steps: 0 }, 0), false);
  });
});

// ---------------------------------------------------------------------------
// Sanity checks for formatting helpers (used by merge)
// ---------------------------------------------------------------------------

describe("formatDuration (merge-relevant cases)", () => {
  it("formats minutes and seconds", () => {
    assert.equal(formatDuration(765_000), "12m 45s");
  });

  it("formats exact minutes", () => {
    assert.equal(formatDuration(300_000), "5m");
  });

  it("formats sub-minute", () => {
    assert.equal(formatDuration(45_000), "45s");
  });

  it("formats sub-second", () => {
    assert.equal(formatDuration(500), "500ms");
  });
});

describe("formatUsd", () => {
  it("formats with 4 decimal places", () => {
    assert.equal(formatUsd(18.5432), "$18.5432");
  });

  it("formats zero", () => {
    assert.equal(formatUsd(0), "$0.0000");
  });
});
