/**
 * handlers/types.ts — NodeHandler plugin interface for the DAGent pipeline.
 *
 * Defines the contract between the orchestration kernel and handler
 * implementations. The kernel dispatches to handlers; handlers execute
 * feature logic and return results.
 *
 * State ownership model:
 * - Handlers are OBSERVERS — they must NOT call completeItem/failItem.
 *   The kernel is the sole state mutator.
 * - For copilot-agent sessions, agents signal their final outcome via the
 *   `report_outcome` SDK tool (see harness/outcome-tool.ts). The kernel
 *   translates the reported outcome into a Command. Sessions that end
 *   without calling `report_outcome` are treated as a hard failure.
 *
 * Built-in handlers: copilot-agent, github-ci-poll, local-exec, triage
 * Custom handlers: local .ts files resolved via dynamic import (sandboxed to repo)
 */

import type { ApmCompiledOutput } from "../apm/types.js";
import type { PipelineState, ItemSummary } from "../types.js";
import type { PipelineLogger } from "../telemetry/index.js";
import type { CopilotClient } from "@github/copilot-sdk";
import type { VersionControl } from "../ports/version-control.js";
import type { StateStore } from "../ports/state-store.js";
import type { Shell } from "../ports/shell.js";
import type { FeatureFilesystem } from "../ports/feature-filesystem.js";
import type { CopilotSessionRunner } from "../ports/copilot-session-runner.js";
import type { TriageLlm } from "../ports/triage-llm.js";
import type { TriageArtifactLoader } from "../ports/triage-artifact-loader.js";
import type { BaselineLoader } from "../ports/baseline-loader.js";
import type { DagCommand } from "../dag-commands.js";

// Re-export for backwards compatibility — the authoritative types live in
// src/dag-commands.ts so both handlers/ and kernel/ can import them
// without creating a layering cycle.
export type {
  DagCommand,
  ResetNodesCommand,
  SalvageDraftCommand,
  SetPendingContextCommand,
  SetTriageRecordCommand,
  ReindexCommand,
} from "../dag-commands.js";

// ---------------------------------------------------------------------------
// NodeContext — input to every handler
// ---------------------------------------------------------------------------

/**
 * Immutable context passed to every handler invocation.
 * The kernel assembles this from pipeline state, APM config, and prior results.
 */
export interface NodeContext {
  /** Pipeline item key (e.g. "backend-dev", "push-app") */
  readonly itemKey: string;
  /** Unique identifier for this specific execution (UUID v4).
   *  Generated by the node wrapper before handler invocation.
   *  Flows through to telemetry, triage, and persisted execution records. */
  readonly executionId: string;
  /** Feature slug */
  readonly slug: string;
  /** Absolute path to the app directory (contains .apm/) */
  readonly appRoot: string;
  /** Absolute path to the repository root */
  readonly repoRoot: string;
  /** Target branch for PRs (e.g. "main") */
  readonly baseBranch: string;
  /** Current in-memory attempt number (1-based) */
  readonly attempt: number;
  /** Combined in-memory + persisted redevelopment cycle count */
  readonly effectiveAttempts: number;
  /** Environment variables from apm.yml config.environment (resolved) */
  readonly environment: Record<string, string>;
  /** Full APM compiled output (read-only) — agents, workflows, config */
  readonly apmContext: ApmCompiledOutput;
  /** Pipeline state snapshot at dispatch time (read-only) */
  readonly pipelineState: Readonly<PipelineState>;
  /** Summary from the most recent failed attempt for this item, if any */
  readonly previousAttempt?: Readonly<ItemSummary>;
  /** Summaries from downstream items that failed (for redevelopment context) */
  readonly downstreamFailures?: ReadonlyArray<Readonly<ItemSummary>>;
  /** All pipeline summaries so far (read-only). Used by agents for context
   *  injection (change manifests, downstream failure context, heartbeats). */
  readonly pipelineSummaries: ReadonlyArray<Readonly<ItemSummary>>;
  /** True when force_run_if_changed directories had changes (auto-skip override) */
  readonly forceRunChanges?: boolean;
  /**
   * Snapshot of per-item base refs captured by the kernel. Used by
   * middlewares (e.g. auto-skip) to compute git diffs against the
   * appropriate upstream baseline.
   */
  readonly preStepRefs: Readonly<Record<string, string>>;
  /**
   * Opaque data bag populated by the kernel from previous handlers' output.
   * Example: kernel auto-captures `{ lastPushedSha: "abc123" }` for deploy nodes,
   * the kernel stores and passes to the downstream github-ci-poll handler.
   */
  readonly handlerData: Readonly<Record<string, unknown>>;
  /**
   * Throttled heartbeat callback — handlers should call this periodically
   * during long-running operations to update flight data for live monitoring.
   */
  readonly onHeartbeat: () => void;
  /**
   * Copilot SDK client instance for LLM-powered handlers.
   * Undefined for non-agent handlers (local-exec, approval, etc.).
   * Agent handlers use this to create sessions and run LLM interactions.
   */
  readonly client?: CopilotClient;
  /**
   * Vendor-agnostic triage LLM port. Used by the triage handler for the
   * RAG→LLM fallback layer. Undefined when LLM fallback is disabled.
   */
  readonly triageLlm?: TriageLlm;
  /**
   * Triage artifact loader port. Hides the `in-progress/<slug>_*.{yml,json}`
   * filesystem convention from the triage handler so the handler stays a
   * pure classifier + command builder.
   */
  readonly triageArtifacts?: TriageArtifactLoader;
  /**
   * Baseline loader port. Optional, advisory — supplies a pre-feature
   * page-error baseline (console / network / uncaught) that the triage
   * handler uses to subtract platform noise from structured failures
   * before classification. Undefined when no baseline source is wired.
   */
  readonly baselineLoader?: BaselineLoader;
  /** Pipeline event logger — single entry point for all telemetry. */
  readonly logger: PipelineLogger;
  /**
   * Version control port — handlers must use this instead of spawning git
   * directly. Provides HEAD SHA, changed-file diffs, and branch operations.
   */
  readonly vcs: VersionControl;
  /**
   * Read-only view of the pipeline state store. Handlers must observe
   * authoritative state through this port rather than importing state
   * modules directly. Full read methods exposed; handlers MUST NOT mutate.
   */
  readonly stateReader: Pick<StateStore, "getStatus">;
  /**
   * Shell port — handlers that need to shell out (local-exec, CI poll,
   * artifact download) must go through this port rather than importing
   * `node:child_process` directly.
   */
  readonly shell: Shell;
  /**
   * Feature workspace filesystem — handlers must read/write feature files
   * (in-progress/ diagnostics, CI artifact staging, tmp dirs) through
   * this port rather than importing `node:fs` / `node:path` directly.
   */
  readonly filesystem: FeatureFilesystem;
  /**
   * Copilot SDK session runner — the copilot-agent handler delegates the
   * actual `sendAndWait` lifecycle to this port. The composition root
   * wires a Node-backed adapter; tests inject a stub.
   */
  readonly copilotSessionRunner: CopilotSessionRunner;

  // ── Failure context (populated when dispatched via on_failure edge) ──

  /** Key of the node that failed and triggered this dispatch (on_failure only). */
  readonly failingNodeKey?: string;
  /** Raw error message from the failing node (on_failure only). */
  readonly rawError?: string;
  /** Computed error signature from the failing node (on_failure only). */
  readonly errorSignature?: string;
  /** Summary snapshot of the failing node's last attempt (on_failure only). */
  readonly failingNodeSummary?: Readonly<ItemSummary>;
  /** Route map from the failing node's on_failure.routes (on_failure only).
   *  Keys are fault domains, values are DAG node keys (or null for graceful degradation). */
  readonly failureRoutes?: Readonly<Record<string, string | null>>;
  /** Parsed structured failure artifact, when the failing handler produced one
   *  (e.g. Playwright JSON reporter). Forwarded from `TriageActivation`.
   *  Kept as `unknown` at this layer — triage narrows on consumption. */
  readonly structuredFailure?: unknown;
}

// ---------------------------------------------------------------------------
// NodeResult — output from every handler
// ---------------------------------------------------------------------------

/**
 * Result returned by a handler after execution.
 * The kernel uses this to update pipeline state, route triage, and flush reports.
 * Handlers MUST NOT call completeItem/failItem — that is the kernel's job.
 */
export interface NodeResult {
  /** Execution outcome — the kernel maps this to pipeline state transitions */
  outcome: "completed" | "failed" | "error";
  /** Human-readable error message (required when outcome is "failed" or "error") */
  errorMessage?: string;
  /** Partial telemetry summary — kernel merges with timing/attempt metadata */
  summary: Partial<ItemSummary>;
  /**
   * Rare control signal to the kernel:
   * - "halt": stop the pipeline immediately (fatal error)
   * - "create-pr": trigger archive + PR publish (used by publish handler)
   * - "salvage-draft": degrade to Draft PR (unfixable error)
   * - "approval-pending": item awaits external approval (watchdog pauses)
   */
  signal?: "halt" | "create-pr" | "salvage-draft" | "approval-pending";
  /**
   * Bag-of-signals for richer handler → kernel communication.
   * Complements the single `signal` field for cases where multiple
   * independent signals need to be communicated (e.g. halt + salvage-draft).
   */
  signals?: Record<string, boolean>;
  /**
   * Opaque output data for downstream handlers.
   * The kernel stores this in `handlerData` for subsequent handler invocations.
   * Example: `{ lastPushedSha: "abc123" }` auto-captured by kernel for deploy nodes.
   */
  handlerOutput?: Record<string, unknown>;
  /**
   * Extracted diagnostic trace from a structured TriageDiagnostic JSON failure.
   * Populated by the copilot-agent handler when the agent's failure message
   * is valid TriageDiagnostic JSON.
   */
  diagnosticTrace?: string;
  /**
   * Declarative graph-mutation commands for the kernel to execute.
   * Handlers produce commands; the kernel's command executor is the sole
   * authority that translates them into state API calls.
   * Processed AFTER signal/signals handling. Order is preserved.
   */
  commands?: DagCommand[];
}

// ---------------------------------------------------------------------------
// DagCommand — declarative graph-mutation protocol
// ---------------------------------------------------------------------------
//
// The authoritative definitions live in `src/dag-commands.ts`. They are
// re-exported at the top of this file so existing `from "./types.js"`
// callers continue to work.

// ---------------------------------------------------------------------------
// SkipResult — structured auto-skip response
// ---------------------------------------------------------------------------

/**
 * Returned by the auto-skip middleware when the workflow manifest's
 * skip rules fire. The dispatcher translates this into a `complete-item`
 * command and uses the reason for summary reporting. `filesChanged` is
 * optional attribution for sentinel-file updates.
 */
export interface SkipResult {
  /** Human-readable reason the item was skipped (logged in summary) */
  reason: string;
  /** Files that changed during skip evaluation (e.g. sentinel files touched) */
  filesChanged?: string[];
}

// ---------------------------------------------------------------------------
// HandlerMetadata — optional self-describing contract for handlers
// ---------------------------------------------------------------------------

/**
 * Optional metadata a handler can declare to describe its data contracts.
 * The kernel uses this for:
 * - Pre-dispatch validation: warn/fail if required inputs are missing from handlerData
 * - Documentation: auto-generate pipeline data-flow diagrams
 * - Handoff tracing: log which handler produced/consumed which keys
 *
 * All fields are optional — handlers without metadata work exactly as before.
 */
export interface HandlerMetadata {
  /** Human-readable description of what this handler does. */
  description?: string;

  /**
   * Keys this handler expects to find in `ctx.handlerData`.
   * Each entry maps a key name to its requirement level.
   * - "required": kernel warns/fails if key is missing at dispatch time
   * - "optional": handler gracefully handles absence
   *
   * Example: `{ "lastPushedSha": "required", "planOutput": "optional" }`
   */
  inputs?: Record<string, "required" | "optional">;

  /**
   * Keys this handler may produce in `result.handlerOutput`.
   * Purely declarative — used for documentation, tracing, and
   * downstream validation (does the consumer's input exist in any upstream's outputs?).
   *
   * Example: `["lastPushedSha", "ciRunId"]`
   */
  outputs?: string[];
}

// ---------------------------------------------------------------------------
// NodeHandler — the plugin interface
// ---------------------------------------------------------------------------

/**
 * Plugin interface for pipeline node execution.
 *
 * Built-in implementations: copilot-agent, github-ci-poll, local-exec.
 * Custom implementations: local .ts files or npm packages (v2).
 *
 * Contract:
 * - `execute()` performs the handler's work and returns a result
 * - Cross-cutting concerns (auto-skip, attempt counting, telemetry hooks,
 *   capability enforcement) are handled by the node middleware chain in
 *   `loop/dispatch/item-dispatch.ts` — handlers stay focused on their work
 * - Handlers are OBSERVERS and must NOT call completeItem/failItem, with one
 *   exception: the triage handler has exclusive state mutation authority
 *   (resetNodes, salvageForDraft, setLastTriageRecord, setPendingContext)
 * - Handlers may call shell commands, read/write files, and interact with external APIs
 * - The kernel is the sole owner of pipeline state transitions for all other handlers
 */
export interface NodeHandler {
  /** Unique handler identifier (e.g. "copilot-agent", "local-exec") */
  readonly name: string;

  /**
   * Optional self-describing metadata. When present, the kernel validates
   * input contracts before dispatch and traces output keys in the event log.
   * Handlers without metadata are fully backward compatible.
   */
  readonly metadata?: HandlerMetadata;

  /**
   * Execute the handler's main logic.
   * @param ctx - Immutable context assembled by the kernel
   * @returns Result describing outcome, telemetry, and optional control signals
   */
  execute(ctx: NodeContext): Promise<NodeResult>;
}
