/**
 * reporting/summary.ts — _SUMMARY.md pipeline executive report writer.
 */

import fs from "node:fs";
import path from "node:path";
import type { ApmCompiledOutput } from "../apm/index.js";
import type { ItemSummary } from "../types.js";
import type { PreviousSummaryTotals } from "../app-types.js";
import { featurePath, ensureFeatureDir } from "../paths/feature-paths.js";
import { computeStepCost } from "./pricing.js";
import { formatDuration, formatUsd, stepIcon } from "./format.js";
import { buildCostAnalysisLines } from "./cost.js";
import { buildCodeIndexLines } from "./code-index-section.js";
import { writeFlightData } from "./flight-data.js";

/** Write a human-readable markdown summary of the pipeline run */
export function writePipelineSummary(
  appRoot: string,
  repoRoot: string,
  featureSlug: string,
  summaries: readonly ItemSummary[],
  apmCtx?: ApmCompiledOutput,
  baseTelemetry?: PreviousSummaryTotals | null,
): void {
  const summaryPath = featurePath(appRoot, featureSlug, "summary");
  ensureFeatureDir(appRoot, featureSlug, "summary");

  // --- Current session totals ---
  const totalMs = summaries.reduce((sum, s) => sum + s.durationMs, 0);
  const completed = summaries.filter((s) => s.outcome === "completed").length;
  const failed = summaries.filter((s) => s.outcome !== "completed").length;
  const allFiles = new Set<string>();
  for (const s of summaries) {
    for (const f of s.filesChanged) allFiles.add(f);
  }
  const totalTokens = summaries.reduce((sum, s) => sum + s.inputTokens + s.outputTokens, 0);
  const totalCost = summaries.reduce((sum, s) => sum + computeStepCost(s), 0);

  // --- Monotonic merge: baseTelemetry was parsed once at boot, just add it ---
  const base = baseTelemetry ?? null;
  const mergedSteps = summaries.length + (base?.steps ?? 0);
  const mergedCompleted = completed + (base?.completed ?? 0);
  const mergedFailed = failed + (base?.failed ?? 0);
  const mergedMs = totalMs + (base?.durationMs ?? 0);
  const mergedFiles = allFiles.size + (base?.filesChanged ?? 0);
  const mergedTokens = totalTokens + (base?.tokens ?? 0);
  const mergedCost = totalCost + (base?.costUsd ?? 0);
  const mergeNote = base ? ` (includes ${base.steps} steps from prior session)` : "";

  const lines: string[] = [
    `# Pipeline Summary — ${featureSlug}`,
    ``,
    `> Auto-generated by the orchestrator on ${new Date().toISOString()}`,
    ``,
    `## Overview`,
    ``,
    `| Metric | Value |`,
    `|---|---|`,
    `| Total steps | ${mergedSteps} (${mergedCompleted} passed, ${mergedFailed} failed/errored)${mergeNote} |`,
    `| Total duration | ${formatDuration(mergedMs)} |`,
    `| Files changed | ${mergedFiles} |`,
    `| Total tokens | ${mergedTokens.toLocaleString()} |`,
    `| **Estimated cost** | **${formatUsd(mergedCost)}** |`,
    ...(mergedFiles > 0 ? [`| Cost per file changed | ${formatUsd(mergedCost / mergedFiles)} |`] : []),
    ``,
  ];

  // --- Per-step detail ---
  lines.push(`## Steps`, ``);

  for (const item of summaries) {

    const icon = stepIcon(item);
    const duration = formatDuration(item.durationMs);
    const attemptTag = item.attempt > 1 ? ` (attempt ${item.attempt})` : "";
    lines.push(`#### ${icon} ${item.label} — \`${item.key}\`${attemptTag}`);
    lines.push(``);
    lines.push(`| | |`);
    lines.push(`|---|---|`);
    lines.push(`| Agent | ${item.agent} |`);
    lines.push(`| Duration | ${duration} |`);
    lines.push(`| Started | ${item.startedAt} |`);
    if (item.errorMessage) {
      lines.push(`| Error | ${item.errorMessage} |`);
    }
    lines.push(``);

    // Tool usage breakdown
    const toolEntries = Object.entries(item.toolCounts);
    if (toolEntries.length > 0) {
      lines.push(`**Tool usage:** ${toolEntries.map(([k, v]) => `${k}: ${v}`).join(", ")}`);
      lines.push(``);
    }

    // What the agent did (intents = reasoning/decisions)
    if (item.intents.length > 0) {
      lines.push(`**What it did & why:**`);
      for (const intent of item.intents) {
        lines.push(`- ${intent}`);
      }
      lines.push(``);
    }

    // Scope of changes
    if (item.filesChanged.length > 0) {
      lines.push(`**Files changed:**`);
      for (const f of item.filesChanged) {
        lines.push(`- \`${f}\``);
      }
      lines.push(``);
    }

    // Key pipeline operations (commits, state transitions)
    const pipelineOps = item.shellCommands.filter((c) => c.isPipelineOp);
    if (pipelineOps.length > 0) {
      lines.push(`**Pipeline operations:**`);
      for (const op of pipelineOps) {
        // Extract the meaningful part of the command
        const short = op.command
          .replace(/^cd [^ ]+ && /, "")
          .replace(repoRoot, ".")
          .slice(0, 150);
        lines.push(`- \`${short}\``);
      }
      lines.push(``);
    }

    // Agent's own summary (executive notes)
    if (item.messages.length > 0) {
      lines.push(`**Agent summary:**`);
      // Use the last message as the executive summary (agents typically summarize at the end)
      const lastMsg = item.messages[item.messages.length - 1];
      // Truncate very long messages but keep enough for context
      const summary = lastMsg.length > 500 ? lastMsg.slice(0, 500) + "…" : lastMsg;
      lines.push(`> ${summary}`);
      lines.push(``);
    }

    lines.push(`---`, ``);
  }

  // --- Aggregate scope of changes ---
  if (allFiles.size > 0) {
    lines.push(`## Scope of Changes`, ``);
    // Group by directory
    const byDir: Record<string, string[]> = {};
    for (const f of allFiles) {
      const dir = f.includes("/") ? f.split("/").slice(0, 2).join("/") : ".";
      (byDir[dir] ??= []).push(f);
    }
    for (const [dir, files] of Object.entries(byDir).sort()) {
      lines.push(`### \`${dir}/\``);
      for (const f of files.sort()) {
        lines.push(`- \`${f}\``);
      }
      lines.push(``);
    }
  }

  // --- Failure timeline (if any failures occurred) ---
  const failures = summaries.filter((s) => s.outcome !== "completed");
  if (failures.length > 0) {
    lines.push(`## Failure Log`, ``);
    lines.push(`| Step | Attempt | Error | Resolution |`);
    lines.push(`|---|---|---|---|`);
    for (const f of failures) {
      // Check if a later run of the same key succeeded
      const laterSuccess = summaries.find(
        (s) => s.key === f.key && s.attempt > f.attempt && s.outcome === "completed",
      );
      const resolution = laterSuccess ? `Resolved on attempt ${laterSuccess.attempt}` : "Unresolved";
      lines.push(`| ${f.key} | ${f.attempt} | ${f.errorMessage ?? "—"} | ${resolution} |`);
    }
    lines.push(``);
  }

  // --- Cost Analysis ---
  lines.push(...buildCostAnalysisLines(summaries, apmCtx));

  // --- Code Index activity (no-op when no code-index.* events were emitted) ---
  lines.push(...buildCodeIndexLines(featurePath(appRoot, featureSlug, "events")));

  try {
    fs.writeFileSync(summaryPath, lines.join("\n"), "utf-8");
    console.log(`\n📋 Pipeline summary written to ${path.relative(repoRoot, summaryPath)}`);
  } catch {
    console.error("  ⚠ Could not write pipeline summary file");
  }

  // --- Structured JSON sidecar for cross-session telemetry merging ---
  // Replaces regex-based parsing with deterministic JSON round-trip.
  const dataPath = featurePath(appRoot, featureSlug, "summary-data");
  ensureFeatureDir(appRoot, featureSlug, "summary-data");
  const data: PreviousSummaryTotals = {
    steps: mergedSteps,
    completed: mergedCompleted,
    failed: mergedFailed,
    durationMs: mergedMs,
    filesChanged: mergedFiles,
    tokens: mergedTokens,
    costUsd: mergedCost,
  };
  try {
    fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), "utf-8");
  } catch {
    console.error("  ⚠ Could not write pipeline summary data file");
  }

  // --- Flight data JSON export (read-only API contract for external dashboards) ---
  writeFlightData(appRoot, featureSlug, summaries);
}
