/**
 * reporting/terminal-log.ts — _TERMINAL-LOG.md chronological event trace writer.
 */

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import type { ApmCompiledOutput } from "../apm/types.js";
import type { ItemSummary } from "../types.js";
import type { PreviousSummaryTotals } from "../app-types.js";
import { featurePath, ensureFeatureDir } from "../adapters/feature-paths.js";
import { computeStepCost } from "./pricing.js";
import { formatDuration, formatUsd, stepIcon } from "./format.js";
import { buildCostAnalysisLines } from "./cost.js";

/**
 * Write a detailed terminal-style log of the pipeline run.
 * Captures every tool call, shell command, intent, and agent summary per step
 * in chronological order — replicating what the user sees in the terminal.
 */
export function writeTerminalLog(
  appRoot: string,
  repoRoot: string,
  baseBranch: string,
  featureSlug: string,
  summaries: readonly ItemSummary[],
  apmCtx?: ApmCompiledOutput,
  baseTelemetry?: PreviousSummaryTotals | null,
): void {
  const logPath = featurePath(appRoot, featureSlug, "terminal-log");
  ensureFeatureDir(appRoot, featureSlug, "terminal-log");

  const totalMs = summaries.reduce((sum, s) => sum + s.durationMs, 0);
  const completed = summaries.filter((s) => s.outcome === "completed").length;
  const failed = summaries.filter((s) => s.outcome !== "completed").length;

  // Pre-compute cost totals for Overview
  const totalTokens = summaries.reduce((sum, s) => sum + s.inputTokens + s.outputTokens, 0);
  const totalCost = summaries.reduce((sum, s) => sum + computeStepCost(s), 0);

  // Monotonic merge: baseTelemetry was parsed once at boot, just add it
  const base = baseTelemetry ?? null;
  const mergedSteps = summaries.length + (base?.steps ?? 0);
  const mergedCompleted = completed + (base?.completed ?? 0);
  const mergedFailed = failed + (base?.failed ?? 0);
  const mergedMs = totalMs + (base?.durationMs ?? 0);
  const mergedTokens = totalTokens + (base?.tokens ?? 0);
  const mergedCost = totalCost + (base?.costUsd ?? 0);
  const mergeNote = base ? ` (includes ${base.steps} steps from prior session)` : "";

  // Compute actual file changes via git diff if possible
  let gitDiffStat = "";
  try {
    const remoteBranch = `origin/${baseBranch}`;
    gitDiffStat = execSync(
      `git diff --stat ${remoteBranch}..HEAD -- . ':!**/.dagent'`,
      { cwd: repoRoot, encoding: "utf-8", timeout: 10_000 },
    ).trim();
  } catch { /* non-fatal */ }

  // Compute git log
  let gitLog = "";
  try {
    const remoteBranch = `origin/${baseBranch}`;
    gitLog = execSync(
      `git log --oneline ${remoteBranch}..HEAD`,
      { cwd: repoRoot, encoding: "utf-8", timeout: 10_000 },
    ).trim();
  } catch { /* non-fatal */ }

  const lines: string[] = [
    `# Terminal Log — ${featureSlug}`,
    ``,
    `> Auto-generated by the orchestrator on ${new Date().toISOString()}`,
    ``,
    `## Overview`,
    ``,
    `| Metric | Value |`,
    `|---|---|`,
    `| Total steps | ${mergedSteps} (${mergedCompleted} passed, ${mergedFailed} failed/errored)${mergeNote} |`,
    `| Total duration | ${formatDuration(mergedMs)} |`,
    `| Feature branch | \`feature/${featureSlug}\` |`,
    `| Base branch | \`${baseBranch}\` |`,
    `| Total tokens | ${mergedTokens.toLocaleString()} |`,
    `| **Estimated cost** | **${formatUsd(mergedCost)}** |`,
    ``,
    `---`,
    ``,
    `## Step-by-Step Execution Log`,
    ``,
  ];

  for (const item of summaries) {
    const icon = stepIcon(item);
    const duration = formatDuration(item.durationMs);
    const attemptTag = item.attempt > 1 ? ` (attempt ${item.attempt})` : "";
    lines.push(`#### ${icon} ${item.label} — \`${item.key}\`${attemptTag}`);
    lines.push(``);
    lines.push(`| | |`);
    lines.push(`|---|---|`);
    lines.push(`| Agent | ${item.agent} |`);
    lines.push(`| Duration | ${duration} |`);
    lines.push(`| Started | ${item.startedAt} |`);
    lines.push(`| Finished | ${item.finishedAt} |`);
    if (item.errorMessage) {
      lines.push(`| Error | ${item.errorMessage} |`);
    }
    lines.push(``);

    // Tool usage breakdown
    const toolEntries = Object.entries(item.toolCounts);
    if (toolEntries.length > 0) {
      lines.push(`**Tool usage:** ${toolEntries.map(([k, v]) => `${k}: ${v}`).join(", ")}`);
      lines.push(``);
    }

    // Chronological event log (interleaved intents, shell commands, file ops)
    // Build a timeline from shell commands (which have timestamps) and intents
    const events: { ts: string; type: string; detail: string }[] = [];

    for (const cmd of item.shellCommands) {
      const short = cmd.command.replace(repoRoot, ".").slice(0, 120);
      const icon = cmd.isPipelineOp ? "📌" : "🖥";
      events.push({ ts: cmd.timestamp, type: icon, detail: short });
    }

    // Intents don't have timestamps, so interleave them at approximate positions
    for (const intent of item.intents) {
      events.push({ ts: "", type: "💭", detail: intent });
    }

    if (events.length > 0) {
      lines.push(`**Execution trace:**`);
      lines.push("```");
      for (const evt of events) {
        const tsPrefix = evt.ts ? `[${evt.ts.slice(11, 19)}] ` : "          ";
        lines.push(`${tsPrefix}${evt.type}  ${evt.detail}`);
      }
      lines.push("```");
      lines.push(``);
    }

    // Files read
    if (item.filesRead.length > 0) {
      lines.push(`**Files read:** ${item.filesRead.map((f) => `\`${f}\``).join(", ")}`);
      lines.push(``);
    }

    // Files changed
    if (item.filesChanged.length > 0) {
      lines.push(`**Files changed:** ${item.filesChanged.map((f) => `\`${f}\``).join(", ")}`);
      lines.push(``);
    }

    // Pipeline operations
    const pipelineOps = item.shellCommands.filter((c) => c.isPipelineOp);
    if (pipelineOps.length > 0) {
      lines.push(`**Pipeline operations:**`);
      for (const op of pipelineOps) {
        const short = op.command.replace(/^cd [^ ]+ && /, "").replace(repoRoot, ".").slice(0, 150);
        lines.push(`- \`${short}\``);
      }
      lines.push(``);
    }

    // Agent summary
    if (item.messages.length > 0) {
      const lastMsg = item.messages[item.messages.length - 1];
      const summary = lastMsg.length > 800 ? lastMsg.slice(0, 800) + "…" : lastMsg;
      lines.push(`**Agent summary:**`);
      lines.push(`> ${summary}`);
      lines.push(``);
    }

    lines.push(`---`, ``);
  }

  // --- Failure Log ---
  const failures = summaries.filter((s) => s.outcome !== "completed");
  if (failures.length > 0) {
    lines.push(`## Failure Log`, ``);
    lines.push(`| Step | Attempt | Timestamp | Error | Resolution |`);
    lines.push(`|---|---|---|---|---|`);
    for (const f of failures) {
      const laterSuccess = summaries.find(
        (s) => s.key === f.key && s.attempt > f.attempt && s.outcome === "completed",
      );
      const resolution = laterSuccess
        ? `Resolved on attempt ${laterSuccess.attempt} (${formatDuration(laterSuccess.durationMs)})`
        : "Unresolved";
      lines.push(`| ${f.key} | ${f.attempt} | ${f.startedAt} | ${f.errorMessage ?? "—"} | ${resolution} |`);
    }
    lines.push(``);
  }

  // --- Git Commit History ---
  if (gitLog) {
    lines.push(`## Git Commit History`, ``);
    lines.push("```");
    lines.push(gitLog);
    lines.push("```");
    lines.push(``);
  }

  // --- Files Changed (diff stat) ---
  if (gitDiffStat) {
    lines.push(`## Files Changed (vs base branch)`, ``);
    lines.push("```");
    lines.push(gitDiffStat);
    lines.push("```");
    lines.push(``);
  }

  // --- Cost Analysis ---
  lines.push(...buildCostAnalysisLines(summaries, apmCtx));

  try {
    fs.writeFileSync(logPath, lines.join("\n"), "utf-8");
  } catch {
    console.error("  ⚠ Could not write terminal log file");
  }
}
