// =============================================================================
// Task Board Schemas
// =============================================================================
// Kanban task board data models — used by both backend API and frontend UI.
// =============================================================================

import { z } from "zod";

/**
 * Valid task statuses for Kanban board columns.
 *
 * - `TODO` — task is pending (default on creation)
 * - `IN_PROGRESS` — task is actively being worked on
 * - `DONE` — task is completed
 */
export const TaskStatusSchema = z.enum(["TODO", "IN_PROGRESS", "DONE"]);

export type TaskStatus = z.infer<typeof TaskStatusSchema>;

/**
 * Full task entity as persisted in Cosmos DB and returned by the API.
 *
 * @example
 * ```json
 * {
 *   "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 *   "workspaceId": "default",
 *   "title": "Implement drag-and-drop",
 *   "status": "TODO",
 *   "createdAt": "2026-04-04T12:00:00.000Z",
 *   "updatedAt": "2026-04-04T12:00:00.000Z"
 * }
 * ```
 */
export const TaskSchema = z.object({
  id: z.string().uuid({ message: "id must be a valid UUID" }),
  workspaceId: z.string().min(1, { message: "workspaceId is required" }),
  title: z.string().min(1, { message: "Title is required" }).max(200, {
    message: "Title must be 200 characters or fewer",
  }),
  status: TaskStatusSchema,
  createdAt: z.string().datetime({ message: "createdAt must be an ISO-8601 datetime string" }),
  updatedAt: z.string().datetime({ message: "updatedAt must be an ISO-8601 datetime string" }),
});

export type Task = z.infer<typeof TaskSchema>;

/**
 * Request body for `POST /tasks` — create a new task.
 *
 * Only `title` is required from the client. `workspaceId` is injected
 * server-side, and all other fields are generated by the backend.
 *
 * @example
 * ```json
 * { "title": "Implement drag-and-drop" }
 * ```
 */
export const CreateTaskSchema = z.object({
  title: z.string().min(1, { message: "Title is required" }).max(200, {
    message: "Title must be 200 characters or fewer",
  }),
});

export type CreateTask = z.infer<typeof CreateTaskSchema>;

/**
 * Request body for `PATCH /tasks/{id}/status` — update a task's status.
 *
 * @example
 * ```json
 * { "status": "IN_PROGRESS" }
 * ```
 */
export const UpdateTaskStatusSchema = z.object({
  status: TaskStatusSchema,
});

export type UpdateTaskStatus = z.infer<typeof UpdateTaskStatusSchema>;
